// Proposed research questions, not approved departments, secured partners or
// demonstrations of a working STANKIN machine. World topic IDs are related
// bibliometric groups; a subtopic is not necessarily the full OpenAlex topic.

export const PISH_TOPIC_UMBRELLA = {
  title: { ru: 'Интеллектуальная точная обработка', en: 'Intelligent precision machining' },
  question: { ru: 'Как изготовить годную деталь, когда изнашивается инструмент и меняется состояние станка?', en: 'How can a machine produce an accepted part as its tool wears and its condition changes?' },
};

export const PISH_TOPIC_FAMILIES = [
  {
    id: 'process-core',
    title: { ru: 'Физика резания и износа', en: 'Cutting and wear physics' },
    why: { ru: 'Чтобы менять режим станка, нужно понимать, откуда берутся износ, вибрации и ошибка детали. Здесь соединяются инструмент, материал и движение станка.', en: 'Changing machine settings requires understanding wear, vibration and part error. This connects tooling, material and machine motion.' },
    role: { ru: 'В СТАНКИН есть работы по резанию, покрытиям и материалам. Это основа проекта; конкретные методы и исполнителей нужно выбрать по статьям и испытаниям.', en: 'STANKIN has papers on machining, coatings and materials. These provide a project base; select specific methods and researchers by examining papers and trials.' },
    gaps: { ru: 'Проверить, какие модели уже работают для выбранной пары материал–инструмент. Подготовить одинаковые условия испытаний и измерить силы, износ и качество поверхности.', en: 'Check which models work for the chosen material–tool pair. Establish matched trials and measure forces, wear and surface quality.' },
    subtopics: [
      {
        id: 'wear-and-friction',
        label: { ru: 'Износ и трение', en: 'Wear and friction' },
        question: { ru: 'Что определяет износ инструмента при обработке выбранного материала?', en: 'What determines tool wear when machining the chosen material?' },
        competencyIds: ['coatings-tribology', 'machining'],
        topicIds: ['T11138'],
        sources: ['cirp-machinability-2024', 'cirp-sustainable-2024'],
        status: 'base',
      },
      {
        id: 'cutting-dynamics',
        label: { ru: 'Силы и вибрации', en: 'Forces and vibration' },
        question: { ru: 'Как силы резания и движение станка меняют размер и поверхность детали?', en: 'How do cutting forces and machine motion affect part dimensions and surface quality?' },
        competencyIds: ['machining', 'modeling-mechanics', 'machine-tools-control'],
        topicIds: ['T10188'],
        sources: ['cirp-machinability-2024', 'cirp-adaptive-2023'],
        status: 'base',
      },
      {
        id: 'material-tool-pair',
        label: { ru: 'Материал и инструмент', en: 'Material and tool' },
        question: { ru: 'Как выбрать геометрию и покрытие инструмента под материал и операцию?', en: 'How should tool geometry and coating be selected for the material and operation?' },
        competencyIds: ['machining', 'coatings-tribology', 'ceramics-composites', 'metals-alloys'],
        topicIds: ['T10188'],
        sources: ['cirp-machinability-2024', 'cirp-sustainable-2024'],
        status: 'base',
      },
    ],
  },
  {
    id: 'measured-quality',
    title: { ru: 'Измерения и качество детали', en: 'Measurement and part quality' },
    why: { ru: 'Управление требует проверяемого сигнала: сколько износилось, где возник дефект, выдержан ли размер. В мировой литературе растёт доля работ по зрению и диагностике; эти темы охватывают разные отрасли.', en: 'Control needs a testable signal: how much wear occurred, where a defect appeared and whether the dimension meets tolerance. Vision and diagnostics account for growing shares of world research across several industries.' },
    role: { ru: 'Есть работы СТАНКИН по метрологии и контролю качества. Для проекта нужно связать измерения детали с сигналами станка; опыт в промышленном зрении проверить отдельно.', en: 'STANKIN has papers on metrology and quality control. The project needs to link part measurements with machine signals; industrial vision experience requires a separate check.' },
    gaps: { ru: 'Нужны датчики, контрольные измерения и общая временная шкала данных. Проверить погрешность, дрейф и пропуски сигналов на реальном станке.', en: 'Sensors, reference measurements and a shared data timebase are needed. Test measurement error, drift and missing signals on a real machine.' },
    subtopics: [
      {
        id: 'sensor-signals',
        label: { ru: 'Сигналы о состоянии', en: 'Condition signals' },
        question: { ru: 'Какие сигналы позволяют отличить износ инструмента от смены режима?', en: 'Which signals distinguish tool wear from a change in operating settings?' },
        competencyIds: ['condition-monitoring', 'metrology-quality', 'machining'],
        topicIds: ['T10220'],
        sources: ['cirp-machinability-2024', 'cirp-metrology-2019'],
        status: 'develop',
      },
      {
        id: 'in-process-measurement',
        label: { ru: 'Измерение на станке', en: 'On-machine measurement' },
        question: { ru: 'Можно ли измерить ошибку детали во время обработки и затем её исправить?', en: 'Can part error be measured during machining and then corrected?' },
        competencyIds: ['metrology-quality', 'machine-tools-control'],
        topicIds: ['T11583'],
        sources: ['cirp-metrology-2019', 'nist-twins'],
        status: 'base',
      },
      {
        id: 'vision-for-defects',
        label: { ru: 'Зрение для поиска дефектов', en: 'Vision for defect detection' },
        question: { ru: 'Какие дефекты система видит на новых деталях и где ошибается?', en: 'Which defects can the system detect on new parts, and where does it fail?' },
        competencyIds: ['ai-data', 'metrology-quality'],
        topicIds: ['T12111'],
        sources: ['effra-sria', 'cirp-metrology-2019'],
        status: 'verify',
      },
    ],
  },
  {
    id: 'predictive-process',
    title: { ru: 'Прогноз и выбор режима', en: 'Prediction and choice of settings' },
    why: { ru: 'Физическая модель объясняет процесс; данные помогают учесть то, что модель пропустила. CIRP 2023 и IEEE Access 2024 уже исследуют такой подход к выбору подачи. Новизну своего метода нужно показать в сравнении с ними.', en: 'A physics model explains the process; data help account for what it misses. CIRP 2023 and IEEE Access 2024 already study this approach to feedrate selection. Show the proposed method’s novelty by comparison with these works.' },
    role: { ru: 'Есть работы по моделированию и обработке. Группа «ИИ и данные» шире ИИ для станков: нужные статьи, людей и программные решения предстоит проверить.', en: 'There are papers on modelling and machining. The “AI and data” group is broader than machine-tool AI: relevant papers, people and software still need checking.' },
    gaps: { ru: 'Нужны данные с разных серий и станков, простой метод для сравнения и испытания на данных, которых модель не видела. Рост публикаций именно по этим трём подтемам отдельно не измерен.', en: 'Data from different batches and machines, a simple comparison method and testing on unseen data are needed. Publication growth for these three specific subtopics has not been measured separately.' },
    subtopics: [
      {
        id: 'physics-with-learned-correction',
        label: { ru: 'Физика с обучаемой поправкой', en: 'Physics with a learned correction' },
        question: { ru: 'Что обучаемая поправка улучшает по сравнению с физической моделью без ИИ?', en: 'What does a learned correction improve over a physics model without AI?' },
        competencyIds: ['modeling-mechanics', 'ai-data', 'machining'],
        topicIds: [],
        sources: ['cirp-adaptive-2023', 'ieee-uncertainty-2024'],
        status: 'develop',
      },
      {
        id: 'prediction-uncertainty',
        label: { ru: 'Ошибка и надёжность прогноза', en: 'Prediction error and reliability' },
        question: { ru: 'В каких режимах прогноз надёжен, а когда нужно вернуться к обычной обработке?', en: 'Under which settings is the prediction reliable, and when should ordinary machining resume?' },
        competencyIds: ['ai-data', 'modeling-mechanics', 'metrology-quality'],
        topicIds: [],
        sources: ['ieee-uncertainty-2024', 'nist-twins'],
        status: 'develop',
      },
      {
        id: 'feedrate-selection',
        label: { ru: 'Выбор подачи', en: 'Feedrate selection' },
        question: { ru: 'Как выбрать подачу, чтобы выдержать допуск и сократить время обработки?', en: 'How can feedrate be chosen to meet tolerance and reduce machining time?' },
        competencyIds: ['machining', 'machine-tools-control', 'modeling-mechanics'],
        topicIds: [],
        sources: ['cirp-adaptive-2023', 'ieee-uncertainty-2024'],
        status: 'partner',
      },
    ],
  },
  {
    id: 'factory-transfer',
    title: { ru: 'Перенос на другие станки и производство', en: 'Transfer to other machines and production' },
    why: { ru: 'Метод для одного стенда ещё не даёт продукт для завода. Нужны подключение к разным станкам, проверка после переноса и совместная работа с роботами и контролем.', en: 'A method for one test bench does not yet provide a factory product. It needs connections to different machines, tests after transfer and coordinated work with robotics and inspection.' },
    role: { ru: 'У СТАНКИН есть работы по станкам, цифровому производству и робототехнике. Для проекта нужно проверить конкретные системы управления, интерфейсы и доступные станки.', en: 'STANKIN has papers on machine tools, digital manufacturing and robotics. Check the specific control systems, interfaces and machines available to the project.' },
    gaps: { ru: 'Потребуются производитель станка или ЧПУ и площадка заказчика. Согласовать доступ к сигналам и разрешённые изменения режима; подтвердить результат на второй платформе.', en: 'A machine or CNC manufacturer and a customer test site will be needed. Agree signal access and permitted setting changes, then confirm the result on a second platform.' },
    subtopics: [
      {
        id: 'cnc-connection',
        label: { ru: 'Подключение к разным ЧПУ', en: 'Connection to different CNC systems' },
        question: { ru: 'Как перенести сбор данных и коррекцию режима на другую систему ЧПУ?', en: 'How can data collection and setting correction transfer to another CNC system?' },
        competencyIds: ['machine-tools-control', 'software-it', 'digital-manufacturing'],
        topicIds: ['T10763'],
        sources: ['nist-twins', 'effra-sria'],
        status: 'partner',
      },
      {
        id: 'model-transfer',
        label: { ru: 'Проверка модели после переноса', en: 'Checking the model after transfer' },
        question: { ru: 'Какие параметры модели придётся менять на втором станке и что можно сохранить?', en: 'Which model parameters must change on a second machine, and which can be retained?' },
        competencyIds: ['digital-manufacturing', 'modeling-mechanics', 'ai-data'],
        topicIds: ['T10763'],
        sources: ['nist-twins', 'ieee-uncertainty-2024'],
        status: 'develop',
      },
      {
        id: 'machine-robot-inspection',
        label: { ru: 'Станок, робот и контроль', en: 'Machine, robot and inspection' },
        question: { ru: 'Как согласовать обработку, загрузку детали и контроль без потери качества?', en: 'How can machining, part loading and inspection be coordinated without losing quality?' },
        competencyIds: ['robotics', 'digital-manufacturing', 'metrology-quality'],
        topicIds: ['T10653'],
        sources: ['effra-sria', 'nist-twins'],
        status: 'partner',
      },
    ],
  },
  {
    id: 'materials-tooling',
    title: { ru: 'Инструмент и материалы под задачу заказчика', en: 'Tooling and materials for the customer’s task' },
    why: { ru: 'Работы по материалам и покрытиям можно связать с прогнозом свойств и ресурса инструмента. В мировой литературе растёт доля тем машинного обучения для материалов и диагностики оборудования. Это широкие темы; они не сводятся к режущему инструменту.', en: 'Materials and coatings research can connect to property and tool-life prediction. Machine learning for materials and equipment diagnostics have growing shares of world literature. These are broad topics, not limited to cutting tools.' },
    role: { ru: 'Материалы и покрытия дают исследовательскую основу. Нужно проверить, какие данные испытаний СТАНКИН можно использовать для обучения моделей и какие задачи требуют партнёра.', en: 'Materials and coatings provide a research base. Check which STANKIN test data can train models and which tasks require a partner.' },
    gaps: { ru: 'Работ с выбранной основной темой OpenAlex нет. Нужны проверка конкретных работ, данные испытаний и сравнение с обычным инструментом.', en: 'No works carry the selected primary OpenAlex topic. Check individual papers, test data and performance against existing tooling.' },
    subtopics: [
      {
        id: 'materials-property-prediction',
        label: { ru: 'Прогноз свойств материалов', en: 'Material-property prediction' },
        question: { ru: 'Можно ли по составу и способу изготовления предсказать нужные свойства?', en: 'Can composition and manufacturing route predict the required properties?' },
        competencyIds: ['ceramics-composites', 'metals-alloys', 'ai-data'],
        topicIds: ['T11948'],
        sources: ['cirp-machinability-2024', 'effra-sria'],
        status: 'verify',
      },
      {
        id: 'task-specific-coating',
        label: { ru: 'Покрытие для конкретной обработки', en: 'Coating for a specific operation' },
        question: { ru: 'Какое покрытие повышает ресурс именно на выбранной детали и режиме?', en: 'Which coating extends tool life for the chosen part and settings?' },
        competencyIds: ['coatings-tribology', 'machining', 'ceramics-composites'],
        topicIds: ['T11138', 'T10188'],
        sources: ['cirp-machinability-2024', 'cirp-sustainable-2024'],
        status: 'base',
      },
      {
        id: 'remaining-tool-life',
        label: { ru: 'Остаточный ресурс инструмента', en: 'Remaining tool life' },
        question: { ru: 'Сколько деталей ещё можно обработать до смены инструмента и насколько надёжен прогноз?', en: 'How many more parts can be machined before a tool change, and how reliable is the prediction?' },
        competencyIds: ['condition-monitoring', 'coatings-tribology', 'machining', 'ai-data'],
        topicIds: ['T10220'],
        sources: ['cirp-machinability-2024', 'nist-twins'],
        status: 'develop',
      },
    ],
  },
];

export const PISH_TOPIC_METHOD_CAVEAT = {
  ru: 'Это предлагаемые исследовательские вопросы. Статус «есть работы» означает публикации по связанным темам; людей, оборудование и готовые методы проверяют отдельно. Мировая динамика относится к широким темам OpenAlex, а не автоматически к каждой подтеме дерева. Если связанной темы нет в расчёте, её рост не оценивается. Ноль работ с основной темой не доказывает отсутствия специалистов и не доказывает научную новизну.',
  en: 'These are proposed research questions. “Published work” means papers on related topics; people, equipment and working methods require separate checks. World trends describe broad OpenAlex topics, not automatically every subtopic in this tree. Without a related topic in the calculation, growth is not estimated. Zero primary-topic works establishes neither absent expertise nor scientific novelty.',
};
