// Названия доменов, областей и подобластей классификации OpenAlex (коды ASJC) на русском и английском.
// Английские названия совпадают с display_name в OpenAlex; русские — устоявшиеся термины.
export const DOMAINS = {
  1: { en: 'Life Sciences', ru: 'Науки о жизни' },
  2: { en: 'Social Sciences', ru: 'Социальные и гуманитарные науки' },
  3: { en: 'Physical Sciences', ru: 'Естественные и технические науки' },
  4: { en: 'Health Sciences', ru: 'Медицина и здравоохранение' },
};

export const FIELDS = {
  11: { en: 'Agricultural and Biological Sciences', ru: 'Сельскохозяйственные и биологические науки', domain: 1 },
  12: { en: 'Arts and Humanities', ru: 'Гуманитарные науки и искусство', domain: 2 },
  13: { en: 'Biochemistry, Genetics and Molecular Biology', ru: 'Биохимия, генетика и молекулярная биология', domain: 1 },
  14: { en: 'Business, Management and Accounting', ru: 'Бизнес, менеджмент и бухгалтерский учёт', domain: 2 },
  15: { en: 'Chemical Engineering', ru: 'Химическая технология', domain: 3 },
  16: { en: 'Chemistry', ru: 'Химия', domain: 3 },
  17: { en: 'Computer Science', ru: 'Компьютерные науки', domain: 3 },
  18: { en: 'Decision Sciences', ru: 'Теория принятия решений', domain: 2 },
  19: { en: 'Earth and Planetary Sciences', ru: 'Науки о Земле и планетах', domain: 3 },
  20: { en: 'Economics, Econometrics and Finance', ru: 'Экономика, эконометрика и финансы', domain: 2 },
  21: { en: 'Energy', ru: 'Энергетика', domain: 3 },
  22: { en: 'Engineering', ru: 'Технические науки', domain: 3 },
  23: { en: 'Environmental Science', ru: 'Науки об окружающей среде', domain: 3 },
  24: { en: 'Immunology and Microbiology', ru: 'Иммунология и микробиология', domain: 1 },
  25: { en: 'Materials Science', ru: 'Материаловедение', domain: 3 },
  26: { en: 'Mathematics', ru: 'Математика', domain: 3 },
  27: { en: 'Medicine', ru: 'Медицина', domain: 4 },
  28: { en: 'Neuroscience', ru: 'Нейронауки', domain: 1 },
  29: { en: 'Nursing', ru: 'Сестринское дело', domain: 4 },
  30: { en: 'Pharmacology, Toxicology and Pharmaceutics', ru: 'Фармакология, токсикология и фармацевтика', domain: 1 },
  31: { en: 'Physics and Astronomy', ru: 'Физика и астрономия', domain: 3 },
  32: { en: 'Psychology', ru: 'Психология', domain: 2 },
  33: { en: 'Social Sciences', ru: 'Социальные науки', domain: 2 },
  34: { en: 'Veterinary', ru: 'Ветеринария', domain: 4 },
  35: { en: 'Dentistry', ru: 'Стоматология', domain: 4 },
  36: { en: 'Health Professions', ru: 'Медицинские профессии', domain: 4 },
};

export const SUBFIELDS = {
  1100: { en: 'General Agricultural and Biological Sciences', ru: 'Сельскохозяйственные и биологические науки (общие вопросы)', field: 11 },
  1101: { en: 'Agricultural and Biological Sciences (miscellaneous)', ru: 'Сельскохозяйственные и биологические науки (разное)', field: 11 },
  1102: { en: 'Agronomy and Crop Science', ru: 'Агрономия и растениеводство', field: 11 },
  1103: { en: 'Animal Science and Zoology', ru: 'Зоотехния и зоология', field: 11 },
  1104: { en: 'Aquatic Science', ru: 'Гидробиология', field: 11 },
  1105: { en: 'Ecology, Evolution, Behavior and Systematics', ru: 'Экология, эволюция, поведение и систематика', field: 11 },
  1106: { en: 'Food Science', ru: 'Пищевые технологии', field: 11 },
  1107: { en: 'Forestry', ru: 'Лесное хозяйство', field: 11 },
  1108: { en: 'Horticulture', ru: 'Садоводство', field: 11 },
  1109: { en: 'Insect Science', ru: 'Энтомология', field: 11 },
  1110: { en: 'Plant Science', ru: 'Биология растений', field: 11 },
  1111: { en: 'Soil Science', ru: 'Почвоведение', field: 11 },
  1200: { en: 'General Arts and Humanities', ru: 'Гуманитарные науки и искусство (общие вопросы)', field: 12 },
  1201: { en: 'Arts and Humanities (miscellaneous)', ru: 'Гуманитарные науки и искусство (разное)', field: 12 },
  1202: { en: 'History', ru: 'История', field: 12 },
  1203: { en: 'Language and Linguistics', ru: 'Языкознание', field: 12 },
  1204: { en: 'Archeology', ru: 'Археология', field: 12 },
  1205: { en: 'Classics', ru: 'Антиковедение', field: 12 },
  1206: { en: 'Conservation', ru: 'Сохранение культурного наследия', field: 12 },
  1207: { en: 'History and Philosophy of Science', ru: 'История и философия науки', field: 12 },
  1208: { en: 'Literature and Literary Theory', ru: 'Литература и литературоведение', field: 12 },
  1209: { en: 'Museology', ru: 'Музееведение', field: 12 },
  1210: { en: 'Music', ru: 'Музыка', field: 12 },
  1211: { en: 'Philosophy', ru: 'Философия', field: 12 },
  1212: { en: 'Religious studies', ru: 'Религиоведение', field: 12 },
  1213: { en: 'Visual Arts and Performing Arts', ru: 'Изобразительное и исполнительское искусство', field: 12 },
  1300: { en: 'General Biochemistry, Genetics and Molecular Biology', ru: 'Биохимия, генетика и молекулярная биология (общие вопросы)', field: 13 },
  1301: { en: 'Biochemistry, Genetics and Molecular Biology (miscellaneous)', ru: 'Биохимия, генетика и молекулярная биология (разное)', field: 13 },
  1302: { en: 'Aging', ru: 'Биология старения', field: 13 },
  1303: { en: 'Biochemistry', ru: 'Биохимия', field: 13 },
  1304: { en: 'Biophysics', ru: 'Биофизика', field: 13 },
  1305: { en: 'Biotechnology', ru: 'Биотехнология', field: 13 },
  1306: { en: 'Cancer Research', ru: 'Онкологические исследования', field: 13 },
  1307: { en: 'Cell Biology', ru: 'Клеточная биология', field: 13 },
  1308: { en: 'Clinical Biochemistry', ru: 'Клиническая биохимия', field: 13 },
  1309: { en: 'Developmental Biology', ru: 'Биология развития', field: 13 },
  1310: { en: 'Endocrinology', ru: 'Эндокринология', field: 13 },
  1311: { en: 'Genetics', ru: 'Генетика', field: 13 },
  1312: { en: 'Molecular Biology', ru: 'Молекулярная биология', field: 13 },
  1313: { en: 'Molecular Medicine', ru: 'Молекулярная медицина', field: 13 },
  1314: { en: 'Physiology', ru: 'Физиология', field: 13 },
  1315: { en: 'Structural Biology', ru: 'Структурная биология', field: 13 },
  1400: { en: 'General Business, Management and Accounting', ru: 'Бизнес, менеджмент и бухгалтерский учёт (общие вопросы)', field: 14 },
  1401: { en: 'Business, Management and Accounting (miscellaneous)', ru: 'Бизнес, менеджмент и бухгалтерский учёт (разное)', field: 14 },
  1402: { en: 'Accounting', ru: 'Бухгалтерский учёт', field: 14 },
  1403: { en: 'Business and International Management', ru: 'Бизнес и международный менеджмент', field: 14 },
  1404: { en: 'Management Information Systems', ru: 'Управленческие информационные системы', field: 14 },
  1405: { en: 'Management of Technology and Innovation', ru: 'Управление технологиями и инновациями', field: 14 },
  1406: { en: 'Marketing', ru: 'Маркетинг', field: 14 },
  1407: { en: 'Organizational Behavior and Human Resource Management', ru: 'Организационное поведение и управление персоналом', field: 14 },
  1408: { en: 'Strategy and Management', ru: 'Стратегия и менеджмент', field: 14 },
  1409: { en: 'Tourism, Leisure and Hospitality Management', ru: 'Туризм, досуг и гостиничный бизнес', field: 14 },
  1410: { en: 'Industrial relations', ru: 'Трудовые отношения', field: 14 },
  1500: { en: 'General Chemical Engineering', ru: 'Химическая технология (общие вопросы)', field: 15 },
  1501: { en: 'Chemical Engineering (miscellaneous)', ru: 'Химическая технология (разное)', field: 15 },
  1502: { en: 'Bioengineering', ru: 'Биоинженерия', field: 15 },
  1503: { en: 'Catalysis', ru: 'Катализ', field: 15 },
  1504: { en: 'Chemical Health and Safety', ru: 'Химическая безопасность', field: 15 },
  1505: { en: 'Colloid and Surface Chemistry', ru: 'Коллоидная химия и химия поверхности', field: 15 },
  1506: { en: 'Filtration and Separation', ru: 'Фильтрация и процессы разделения', field: 15 },
  1507: { en: 'Fluid Flow and Transfer Processes', ru: 'Гидродинамика и тепломассоперенос', field: 15 },
  1508: { en: 'Process Chemistry and Technology', ru: 'Химико-технологические процессы', field: 15 },
  1600: { en: 'General Chemistry', ru: 'Химия (общие вопросы)', field: 16 },
  1601: { en: 'Chemistry (miscellaneous)', ru: 'Химия (разное)', field: 16 },
  1602: { en: 'Analytical Chemistry', ru: 'Аналитическая химия', field: 16 },
  1603: { en: 'Electrochemistry', ru: 'Электрохимия', field: 16 },
  1604: { en: 'Inorganic Chemistry', ru: 'Неорганическая химия', field: 16 },
  1605: { en: 'Organic Chemistry', ru: 'Органическая химия', field: 16 },
  1606: { en: 'Physical and Theoretical Chemistry', ru: 'Физическая и теоретическая химия', field: 16 },
  1607: { en: 'Spectroscopy', ru: 'Спектроскопия', field: 16 },
  1700: { en: 'General Computer Science', ru: 'Компьютерные науки (общие вопросы)', field: 17 },
  1701: { en: 'Computer Science (miscellaneous)', ru: 'Компьютерные науки (разное)', field: 17 },
  1702: { en: 'Artificial Intelligence', ru: 'Искусственный интеллект', field: 17 },
  1703: { en: 'Computational Theory and Mathematics', ru: 'Теория вычислений', field: 17 },
  1704: { en: 'Computer Graphics and Computer-Aided Design', ru: 'Компьютерная графика и автоматизированное проектирование', field: 17 },
  1705: { en: 'Computer Networks and Communications', ru: 'Компьютерные сети и коммуникации', field: 17 },
  1706: { en: 'Computer Science Applications', ru: 'Прикладная информатика', field: 17 },
  1707: { en: 'Computer Vision and Pattern Recognition', ru: 'Компьютерное зрение и распознавание образов', field: 17 },
  1708: { en: 'Hardware and Architecture', ru: 'Аппаратное обеспечение и архитектура компьютеров', field: 17 },
  1709: { en: 'Human-Computer Interaction', ru: 'Человеко-компьютерное взаимодействие', field: 17 },
  1710: { en: 'Information Systems', ru: 'Информационные системы', field: 17 },
  1711: { en: 'Signal Processing', ru: 'Обработка сигналов', field: 17 },
  1712: { en: 'Software', ru: 'Программное обеспечение', field: 17 },
  1800: { en: 'General Decision Sciences', ru: 'Теория принятия решений (общие вопросы)', field: 18 },
  1801: { en: 'Decision Sciences (miscellaneous)', ru: 'Теория принятия решений (разное)', field: 18 },
  1802: { en: 'Information Systems and Management', ru: 'Информационные системы в управлении', field: 18 },
  1803: { en: 'Management Science and Operations Research', ru: 'Исследование операций и методы управления', field: 18 },
  1804: { en: 'Statistics, Probability and Uncertainty', ru: 'Статистика, вероятность и неопределённость', field: 18 },
  1900: { en: 'General Earth and Planetary Sciences', ru: 'Науки о Земле и планетах (общие вопросы)', field: 19 },
  1901: { en: 'Earth and Planetary Sciences (miscellaneous)', ru: 'Науки о Земле и планетах (разное)', field: 19 },
  1902: { en: 'Atmospheric Science', ru: 'Науки об атмосфере', field: 19 },
  1903: { en: 'Computers in Earth Sciences', ru: 'Компьютерные методы в науках о Земле', field: 19 },
  1904: { en: 'Earth-Surface Processes', ru: 'Процессы на поверхности Земли', field: 19 },
  1905: { en: 'Economic Geology', ru: 'Геология полезных ископаемых', field: 19 },
  1906: { en: 'Geochemistry and Petrology', ru: 'Геохимия и петрология', field: 19 },
  1907: { en: 'Geology', ru: 'Геология', field: 19 },
  1908: { en: 'Geophysics', ru: 'Геофизика', field: 19 },
  1909: { en: 'Geotechnical Engineering and Engineering Geology', ru: 'Геотехника и инженерная геология', field: 19 },
  1910: { en: 'Oceanography', ru: 'Океанология', field: 19 },
  1911: { en: 'Paleontology', ru: 'Палеонтология', field: 19 },
  1912: { en: 'Space and Planetary Science', ru: 'Космические исследования и планетология', field: 19 },
  1913: { en: 'Stratigraphy', ru: 'Стратиграфия', field: 19 },
  2000: { en: 'General Economics, Econometrics and Finance', ru: 'Экономика, эконометрика и финансы (общие вопросы)', field: 20 },
  2001: { en: 'Economics, Econometrics and Finance (miscellaneous)', ru: 'Экономика, эконометрика и финансы (разное)', field: 20 },
  2002: { en: 'Economics and Econometrics', ru: 'Экономика и эконометрика', field: 20 },
  2003: { en: 'Finance', ru: 'Финансы', field: 20 },
  2100: { en: 'General Energy', ru: 'Энергетика (общие вопросы)', field: 21 },
  2101: { en: 'Energy (miscellaneous)', ru: 'Энергетика (разное)', field: 21 },
  2102: { en: 'Energy Engineering and Power Technology', ru: 'Энергетическая техника и технологии', field: 21 },
  2103: { en: 'Fuel Technology', ru: 'Технология топлива', field: 21 },
  2104: { en: 'Nuclear Energy and Engineering', ru: 'Ядерная энергетика и технологии', field: 21 },
  2105: { en: 'Renewable Energy, Sustainability and the Environment', ru: 'Возобновляемая энергетика, устойчивое развитие и экология', field: 21 },
  2200: { en: 'General Engineering', ru: 'Технические науки (общие вопросы)', field: 22 },
  2201: { en: 'Engineering (miscellaneous)', ru: 'Технические науки (разное)', field: 22 },
  2202: { en: 'Aerospace Engineering', ru: 'Авиационная и ракетно-космическая техника', field: 22 },
  2203: { en: 'Automotive Engineering', ru: 'Автомобилестроение', field: 22 },
  2204: { en: 'Biomedical Engineering', ru: 'Биомедицинская инженерия', field: 22 },
  2205: { en: 'Civil and Structural Engineering', ru: 'Строительство и строительные конструкции', field: 22 },
  2206: { en: 'Computational Mechanics', ru: 'Вычислительная механика', field: 22 },
  2207: { en: 'Control and Systems Engineering', ru: 'Системы управления и системная инженерия', field: 22 },
  2208: { en: 'Electrical and Electronic Engineering', ru: 'Электротехника и электроника', field: 22 },
  2209: { en: 'Industrial and Manufacturing Engineering', ru: 'Машиностроительное производство и промышленная инженерия', field: 22 },
  2210: { en: 'Mechanical Engineering', ru: 'Машиностроение', field: 22 },
  2211: { en: 'Mechanics of Materials', ru: 'Механика материалов', field: 22 },
  2212: { en: 'Ocean Engineering', ru: 'Морская техника и океанотехника', field: 22 },
  2213: { en: 'Safety, Risk, Reliability and Quality', ru: 'Безопасность, риск, надёжность и качество', field: 22 },
  2214: { en: 'Media Technology', ru: 'Медиатехнологии', field: 22 },
  2215: { en: 'Building and Construction', ru: 'Здания и строительные технологии', field: 22 },
  2216: { en: 'Architecture', ru: 'Архитектура', field: 22 },
  2300: { en: 'General Environmental Science', ru: 'Науки об окружающей среде (общие вопросы)', field: 23 },
  2301: { en: 'Environmental Science (miscellaneous)', ru: 'Науки об окружающей среде (разное)', field: 23 },
  2302: { en: 'Ecological Modeling', ru: 'Экологическое моделирование', field: 23 },
  2303: { en: 'Ecology', ru: 'Экология', field: 23 },
  2304: { en: 'Environmental Chemistry', ru: 'Химия окружающей среды', field: 23 },
  2305: { en: 'Environmental Engineering', ru: 'Инженерная экология', field: 23 },
  2306: { en: 'Global and Planetary Change', ru: 'Глобальные изменения климата и окружающей среды', field: 23 },
  2307: { en: 'Health, Toxicology and Mutagenesis', ru: 'Токсикология, мутагенез и здоровье человека', field: 23 },
  2308: { en: 'Management, Monitoring, Policy and Law', ru: 'Экологический менеджмент, мониторинг, политика и право', field: 23 },
  2309: { en: 'Nature and Landscape Conservation', ru: 'Охрана природы и ландшафтов', field: 23 },
  2310: { en: 'Pollution', ru: 'Загрязнение окружающей среды', field: 23 },
  2311: { en: 'Waste Management and Disposal', ru: 'Обращение с отходами и их утилизация', field: 23 },
  2312: { en: 'Water Science and Technology', ru: 'Гидрология и водные технологии', field: 23 },
  2400: { en: 'General Immunology and Microbiology', ru: 'Иммунология и микробиология (общие вопросы)', field: 24 },
  2401: { en: 'Immunology and Microbiology (miscellaneous)', ru: 'Иммунология и микробиология (разное)', field: 24 },
  2402: { en: 'Applied Microbiology and Biotechnology', ru: 'Прикладная микробиология и биотехнология', field: 24 },
  2403: { en: 'Immunology', ru: 'Иммунология', field: 24 },
  2404: { en: 'Microbiology', ru: 'Микробиология', field: 24 },
  2405: { en: 'Parasitology', ru: 'Паразитология', field: 24 },
  2406: { en: 'Virology', ru: 'Вирусология', field: 24 },
  2500: { en: 'General Materials Science', ru: 'Материаловедение (общие вопросы)', field: 25 },
  2501: { en: 'Materials Science (miscellaneous)', ru: 'Материаловедение (разное)', field: 25 },
  2502: { en: 'Biomaterials', ru: 'Биоматериалы', field: 25 },
  2503: { en: 'Ceramics and Composites', ru: 'Керамика и композиты', field: 25 },
  2504: { en: 'Electronic, Optical and Magnetic Materials', ru: 'Электронные, оптические и магнитные материалы', field: 25 },
  2505: { en: 'Materials Chemistry', ru: 'Химия материалов', field: 25 },
  2506: { en: 'Metals and Alloys', ru: 'Металлы и сплавы', field: 25 },
  2507: { en: 'Polymers and Plastics', ru: 'Полимеры и пластмассы', field: 25 },
  2508: { en: 'Surfaces, Coatings and Films', ru: 'Поверхности, покрытия и плёнки', field: 25 },
  2600: { en: 'General Mathematics', ru: 'Математика (общие вопросы)', field: 26 },
  2601: { en: 'Mathematics (miscellaneous)', ru: 'Математика (разное)', field: 26 },
  2602: { en: 'Algebra and Number Theory', ru: 'Алгебра и теория чисел', field: 26 },
  2603: { en: 'Analysis', ru: 'Математический анализ', field: 26 },
  2604: { en: 'Applied Mathematics', ru: 'Прикладная математика', field: 26 },
  2605: { en: 'Computational Mathematics', ru: 'Вычислительная математика', field: 26 },
  2606: { en: 'Control and Optimization', ru: 'Теория управления и оптимизация', field: 26 },
  2607: { en: 'Discrete Mathematics and Combinatorics', ru: 'Дискретная математика и комбинаторика', field: 26 },
  2608: { en: 'Geometry and Topology', ru: 'Геометрия и топология', field: 26 },
  2609: { en: 'Logic', ru: 'Математическая логика', field: 26 },
  2610: { en: 'Mathematical Physics', ru: 'Математическая физика', field: 26 },
  2611: { en: 'Modeling and Simulation', ru: 'Математическое и имитационное моделирование', field: 26 },
  2612: { en: 'Numerical Analysis', ru: 'Численные методы', field: 26 },
  2613: { en: 'Statistics and Probability', ru: 'Теория вероятностей и математическая статистика', field: 26 },
  2614: { en: 'Theoretical Computer Science', ru: 'Теоретическая информатика', field: 26 },
  2700: { en: 'General Medicine', ru: 'Медицина (общие вопросы)', field: 27 },
  2701: { en: 'Medicine (miscellaneous)', ru: 'Медицина (разное)', field: 27 },
  2702: { en: 'Anatomy', ru: 'Анатомия', field: 27 },
  2703: { en: 'Anesthesiology and Pain Medicine', ru: 'Анестезиология и лечение боли', field: 27 },
  2704: { en: 'Biochemistry', ru: 'Медицинская биохимия', field: 27 },
  2705: { en: 'Cardiology and Cardiovascular Medicine', ru: 'Кардиология и сердечно-сосудистые заболевания', field: 27 },
  2706: { en: 'Critical Care and Intensive Care Medicine', ru: 'Реаниматология и интенсивная терапия', field: 27 },
  2707: { en: 'Complementary and alternative medicine', ru: 'Комплементарная и альтернативная медицина', field: 27 },
  2708: { en: 'Dermatology', ru: 'Дерматология', field: 27 },
  2709: { en: 'Drug Guides', ru: 'Справочники лекарственных средств', field: 27 },
  2710: { en: 'Embryology', ru: 'Эмбриология', field: 27 },
  2711: { en: 'Emergency Medicine', ru: 'Неотложная медицина', field: 27 },
  2712: { en: 'Endocrinology, Diabetes and Metabolism', ru: 'Эндокринология, диабет и обмен веществ', field: 27 },
  2713: { en: 'Epidemiology', ru: 'Эпидемиология', field: 27 },
  2714: { en: 'Family Practice', ru: 'Общая врачебная практика', field: 27 },
  2715: { en: 'Gastroenterology', ru: 'Гастроэнтерология', field: 27 },
  2716: { en: 'Genetics', ru: 'Клиническая генетика', field: 27 },
  2717: { en: 'Geriatrics and Gerontology', ru: 'Гериатрия и геронтология', field: 27 },
  2718: { en: 'Health Informatics', ru: 'Медицинская информатика', field: 27 },
  2719: { en: 'Health Policy', ru: 'Политика здравоохранения', field: 27 },
  2720: { en: 'Hematology', ru: 'Гематология', field: 27 },
  2721: { en: 'Hepatology', ru: 'Гепатология', field: 27 },
  2722: { en: 'Histology', ru: 'Гистология', field: 27 },
  2723: { en: 'Immunology and Allergy', ru: 'Иммунология и аллергология', field: 27 },
  2724: { en: 'Internal Medicine', ru: 'Внутренние болезни', field: 27 },
  2725: { en: 'Infectious Diseases', ru: 'Инфекционные болезни', field: 27 },
  2726: { en: 'Microbiology', ru: 'Медицинская микробиология', field: 27 },
  2727: { en: 'Nephrology', ru: 'Нефрология', field: 27 },
  2728: { en: 'Neurology', ru: 'Клиническая неврология', field: 27 },
  2729: { en: 'Obstetrics and Gynecology', ru: 'Акушерство и гинекология', field: 27 },
  2730: { en: 'Oncology', ru: 'Онкология', field: 27 },
  2731: { en: 'Ophthalmology', ru: 'Офтальмология', field: 27 },
  2732: { en: 'Orthopedics and Sports Medicine', ru: 'Ортопедия и спортивная медицина', field: 27 },
  2733: { en: 'Otorhinolaryngology', ru: 'Оториноларингология', field: 27 },
  2734: { en: 'Pathology and Forensic Medicine', ru: 'Патология и судебная медицина', field: 27 },
  2735: { en: 'Pediatrics, Perinatology and Child Health', ru: 'Педиатрия, перинатология и охрана здоровья детей', field: 27 },
  2736: { en: 'Pharmacology', ru: 'Клиническая фармакология', field: 27 },
  2737: { en: 'Physiology', ru: 'Медицинская физиология', field: 27 },
  2738: { en: 'Psychiatry and Mental health', ru: 'Психиатрия и психическое здоровье', field: 27 },
  2739: { en: 'Public Health, Environmental and Occupational Health', ru: 'Общественное здоровье, гигиена и медицина труда', field: 27 },
  2740: { en: 'Pulmonary and Respiratory Medicine', ru: 'Пульмонология', field: 27 },
  2741: { en: 'Radiology, Nuclear Medicine and Imaging', ru: 'Радиология, ядерная медицина и медицинская визуализация', field: 27 },
  2742: { en: 'Rehabilitation', ru: 'Реабилитация', field: 27 },
  2743: { en: 'Reproductive Medicine', ru: 'Репродуктивная медицина', field: 27 },
  2744: { en: 'Reviews and References (medical)', ru: 'Медицинские обзоры и справочники', field: 27 },
  2745: { en: 'Rheumatology', ru: 'Ревматология', field: 27 },
  2746: { en: 'Surgery', ru: 'Хирургия', field: 27 },
  2747: { en: 'Transplantation', ru: 'Трансплантология', field: 27 },
  2748: { en: 'Urology', ru: 'Урология', field: 27 },
  2800: { en: 'General Neuroscience', ru: 'Нейронауки (общие вопросы)', field: 28 },
  2801: { en: 'Neuroscience (miscellaneous)', ru: 'Нейронауки (разное)', field: 28 },
  2802: { en: 'Behavioral Neuroscience', ru: 'Нейробиология поведения', field: 28 },
  2803: { en: 'Biological Psychiatry', ru: 'Биологическая психиатрия', field: 28 },
  2804: { en: 'Cellular and Molecular Neuroscience', ru: 'Клеточная и молекулярная нейробиология', field: 28 },
  2805: { en: 'Cognitive Neuroscience', ru: 'Когнитивная нейронаука', field: 28 },
  2806: { en: 'Developmental Neuroscience', ru: 'Нейробиология развития', field: 28 },
  2807: { en: 'Endocrine and Autonomic Systems', ru: 'Эндокринная и вегетативная регуляция', field: 28 },
  2808: { en: 'Neurology', ru: 'Неврология', field: 28 },
  2809: { en: 'Sensory Systems', ru: 'Сенсорные системы', field: 28 },
  2900: { en: 'General Nursing', ru: 'Сестринское дело (общие вопросы)', field: 29 },
  2901: { en: 'Nursing (miscellaneous)', ru: 'Сестринское дело (разное)', field: 29 },
  2902: { en: 'Advanced and Specialized Nursing', ru: 'Специализированный сестринский уход', field: 29 },
  2903: { en: 'Assessment and Diagnosis', ru: 'Оценка состояния пациента и диагностика', field: 29 },
  2904: { en: 'Care Planning', ru: 'Планирование ухода', field: 29 },
  2905: { en: 'Community and Home Care', ru: 'Патронаж и уход на дому', field: 29 },
  2906: { en: 'Critical Care Nursing', ru: 'Сестринский уход в интенсивной терапии', field: 29 },
  2907: { en: 'Emergency Nursing', ru: 'Сестринский уход в неотложной помощи', field: 29 },
  2908: { en: 'Fundamentals and skills', ru: 'Основы сестринского дела', field: 29 },
  2909: { en: 'Gerontology', ru: 'Геронтология', field: 29 },
  2910: { en: 'Issues, ethics and legal aspects', ru: 'Этические и правовые вопросы здравоохранения', field: 29 },
  2911: { en: 'Leadership and Management', ru: 'Лидерство и управление в здравоохранении', field: 29 },
  2912: { en: 'LPN and LVN', ru: 'Практические медицинские сёстры', field: 29 },
  2913: { en: 'Maternity and Midwifery', ru: 'Охрана материнства и акушерское дело', field: 29 },
  2914: { en: 'Medical–Surgical Nursing', ru: 'Сестринский уход в терапии и хирургии', field: 29 },
  2915: { en: 'Nurse Assisting', ru: 'Младший сестринский персонал', field: 29 },
  2916: { en: 'Nutrition and Dietetics', ru: 'Питание и диетология', field: 29 },
  2917: { en: 'Oncology (nursing)', ru: 'Сестринский уход в онкологии', field: 29 },
  2918: { en: 'Pathophysiology', ru: 'Патофизиология', field: 29 },
  2919: { en: 'Pediatrics', ru: 'Сестринский уход в педиатрии', field: 29 },
  2920: { en: 'Pharmacology (nursing)', ru: 'Фармакология в сестринском деле', field: 29 },
  2921: { en: 'Psychiatric Mental Health', ru: 'Сестринский уход в психиатрии', field: 29 },
  2922: { en: 'Research and Theory', ru: 'Теория и исследования в сестринском деле', field: 29 },
  2923: { en: 'Review and Exam Preparation', ru: 'Обзоры и подготовка к экзаменам', field: 29 },
  3000: { en: 'General Pharmacology, Toxicology and Pharmaceutics', ru: 'Фармакология, токсикология и фармацевтика (общие вопросы)', field: 30 },
  3001: { en: 'Pharmacology, Toxicology and Pharmaceutics (miscellaneous)', ru: 'Фармакология, токсикология и фармацевтика (разное)', field: 30 },
  3002: { en: 'Drug Discovery', ru: 'Разработка лекарственных средств', field: 30 },
  3003: { en: 'Pharmaceutical Science', ru: 'Фармацевтические науки', field: 30 },
  3004: { en: 'Pharmacology', ru: 'Фармакология', field: 30 },
  3005: { en: 'Toxicology', ru: 'Токсикология', field: 30 },
  3100: { en: 'General Physics and Astronomy', ru: 'Физика и астрономия (общие вопросы)', field: 31 },
  3101: { en: 'Physics and Astronomy (miscellaneous)', ru: 'Физика и астрономия (разное)', field: 31 },
  3102: { en: 'Acoustics and Ultrasonics', ru: 'Акустика и ультразвук', field: 31 },
  3103: { en: 'Astronomy and Astrophysics', ru: 'Астрономия и астрофизика', field: 31 },
  3104: { en: 'Condensed Matter Physics', ru: 'Физика конденсированного состояния', field: 31 },
  3105: { en: 'Instrumentation', ru: 'Приборостроение и измерительная техника', field: 31 },
  3106: { en: 'Nuclear and High Energy Physics', ru: 'Ядерная физика и физика высоких энергий', field: 31 },
  3107: { en: 'Atomic and Molecular Physics, and Optics', ru: 'Атомная и молекулярная физика, оптика', field: 31 },
  3108: { en: 'Radiation', ru: 'Радиационная физика', field: 31 },
  3109: { en: 'Statistical and Nonlinear Physics', ru: 'Статистическая и нелинейная физика', field: 31 },
  3110: { en: 'Surfaces and Interfaces', ru: 'Физика поверхности и границ раздела', field: 31 },
  3200: { en: 'General Psychology', ru: 'Психология (общие вопросы)', field: 32 },
  3201: { en: 'Psychology (miscellaneous)', ru: 'Психология (разное)', field: 32 },
  3202: { en: 'Applied Psychology', ru: 'Прикладная психология', field: 32 },
  3203: { en: 'Clinical Psychology', ru: 'Клиническая психология', field: 32 },
  3204: { en: 'Developmental and Educational Psychology', ru: 'Психология развития и педагогическая психология', field: 32 },
  3205: { en: 'Experimental and Cognitive Psychology', ru: 'Экспериментальная и когнитивная психология', field: 32 },
  3206: { en: 'Neuropsychology and Physiological Psychology', ru: 'Нейропсихология и психофизиология', field: 32 },
  3207: { en: 'Social Psychology', ru: 'Социальная психология', field: 32 },
  3300: { en: 'General Social Sciences', ru: 'Социальные науки (общие вопросы)', field: 33 },
  3301: { en: 'Social Sciences (miscellaneous)', ru: 'Социальные науки (разное)', field: 33 },
  3302: { en: 'Archeology', ru: 'Археология', field: 33 },
  3303: { en: 'Development', ru: 'Социально-экономическое развитие', field: 33 },
  3304: { en: 'Education', ru: 'Педагогика и образование', field: 33 },
  3305: { en: 'Geography, Planning and Development', ru: 'География, планирование и развитие территорий', field: 33 },
  3306: { en: 'Health', ru: 'Социальные аспекты здоровья', field: 33 },
  3307: { en: 'Human Factors and Ergonomics', ru: 'Эргономика и человеческий фактор', field: 33 },
  3308: { en: 'Law', ru: 'Право', field: 33 },
  3309: { en: 'Library and Information Sciences', ru: 'Библиотековедение и информационные науки', field: 33 },
  3310: { en: 'Linguistics and Language', ru: 'Лингвистика', field: 33 },
  3311: { en: 'Safety Research', ru: 'Безопасность жизнедеятельности', field: 33 },
  3312: { en: 'Sociology and Political Science', ru: 'Социология и политология', field: 33 },
  3313: { en: 'Transportation', ru: 'Транспорт', field: 33 },
  3314: { en: 'Anthropology', ru: 'Антропология', field: 33 },
  3315: { en: 'Communication', ru: 'Коммуникация и медиа', field: 33 },
  3316: { en: 'Cultural Studies', ru: 'Культурология', field: 33 },
  3317: { en: 'Demography', ru: 'Демография', field: 33 },
  3318: { en: 'Gender Studies', ru: 'Гендерные исследования', field: 33 },
  3319: { en: 'Life-span and Life-course Studies', ru: 'Исследования жизненного пути', field: 33 },
  3320: { en: 'Political Science and International Relations', ru: 'Политология и международные отношения', field: 33 },
  3321: { en: 'Public Administration', ru: 'Государственное и муниципальное управление', field: 33 },
  3322: { en: 'Urban Studies', ru: 'Урбанистика', field: 33 },
  3400: { en: 'General Veterinary', ru: 'Ветеринария (общие вопросы)', field: 34 },
  3401: { en: 'Veterinary (miscellaneous)', ru: 'Ветеринария (разное)', field: 34 },
  3402: { en: 'Equine', ru: 'Ветеринария лошадей', field: 34 },
  3403: { en: 'Food Animals', ru: 'Ветеринария продуктивных животных', field: 34 },
  3404: { en: 'Small Animals', ru: 'Ветеринария мелких домашних животных', field: 34 },
  3500: { en: 'General Dentistry', ru: 'Стоматология (общие вопросы)', field: 35 },
  3501: { en: 'Dentistry (miscellaneous)', ru: 'Стоматология (разное)', field: 35 },
  3502: { en: 'Dental Assisting', ru: 'Ассистирование в стоматологии', field: 35 },
  3503: { en: 'Dental Hygiene', ru: 'Гигиена полости рта', field: 35 },
  3504: { en: 'Oral Surgery', ru: 'Хирургическая стоматология', field: 35 },
  3505: { en: 'Orthodontics', ru: 'Ортодонтия', field: 35 },
  3506: { en: 'Periodontics', ru: 'Пародонтология', field: 35 },
  3600: { en: 'General Health Professions', ru: 'Медицинские профессии (общие вопросы)', field: 36 },
  3601: { en: 'Health Professions (miscellaneous)', ru: 'Медицинские профессии (разное)', field: 36 },
  3602: { en: 'Chiropractics', ru: 'Хиропрактика', field: 36 },
  3603: { en: 'Complementary and Manual Therapy', ru: 'Мануальная и комплементарная терапия', field: 36 },
  3604: { en: 'Emergency Medical Services', ru: 'Скорая медицинская помощь', field: 36 },
  3605: { en: 'Health Information Management', ru: 'Управление медицинской информацией', field: 36 },
  3606: { en: 'Medical Assisting and Transcription', ru: 'Медицинское ассистирование и документирование', field: 36 },
  3607: { en: 'Medical Laboratory Technology', ru: 'Клиническая лабораторная диагностика', field: 36 },
  3608: { en: 'Medical Terminology', ru: 'Медицинская терминология', field: 36 },
  3609: { en: 'Occupational Therapy', ru: 'Эрготерапия', field: 36 },
  3610: { en: 'Optometry', ru: 'Оптометрия', field: 36 },
  3611: { en: 'Pharmacy', ru: 'Фармация', field: 36 },
  3612: { en: 'Physical Therapy, Sports Therapy and Rehabilitation', ru: 'Физическая терапия, спортивная медицина и реабилитация', field: 36 },
  3613: { en: 'Podiatry', ru: 'Подиатрия', field: 36 },
  3614: { en: 'Radiological and Ultrasound Technology', ru: 'Лучевая и ультразвуковая диагностика', field: 36 },
  3615: { en: 'Respiratory Care', ru: 'Респираторная терапия', field: 36 },
  3616: { en: 'Speech and Hearing', ru: 'Логопедия и сурдология', field: 36 },
};
