import { esc, figure, table, cell, text } from './kit.mjs';
import { pishLoop, cohortsChart } from '../charts/pish.mjs';
import { PISH_SOURCES, PISH_REQUIREMENTS, PISH_MINIMUMS, PISH_CANDIDATES, PISH_REVIEWED_AT } from '../../content/pish.mjs';

const L=(ctx,ru,en)=>ctx.lang==='en'?en:ru;
const phrase=(ctx,v)=>typeof v==='string'?v:v?.[ctx.lang]??v?.ru??'';
const value=(ctx,n,d=2)=>n==null?'—':ctx.dec(n,d);
const percent=(ctx,n)=>n==null?'—':ctx.pct(n,1);
const change=(ctx,n)=>n==null?'—':`${n>0?'+':''}${ctx.pct(n,1)}`;
const sourceIds=(ctx,ids)=>`<span class="pish-source-links">${esc(L(ctx,'Источники: ','Sources: '))}${(ids??[]).map(id=>{const i=PISH_SOURCES.findIndex(x=>x.id===id);const s=PISH_SOURCES[i];return s?`<a href="#pish-source-${esc(id)}" title="${esc(phrase(ctx,s.title))}" aria-label="${esc(phrase(ctx,s.title))}">${String(i+1).padStart(2,'0')}</a>`:'';}).join(' · ')}</span>`;
const periodLabel=(ctx,key)=>key ? (ctx.model.pish.period?.[key]??(key==='p1'?[2016,2020]:[2021,2025])).join('–') : `${ctx.model.pish.period?.from??2016}–${ctx.model.pish.period?.to??2025}`;
const interval=(ctx,ci,d=3)=>ci?.lower!=null&&ci?.upper!=null?`${value(ctx,ci.lower,d)} … ${value(ctx,ci.upper,d)}`:L(ctx,'Мало данных','Too little data');
const section=(ctx,id,n,title,sub,body)=>`<section class="section pish-section" id="${id}" aria-labelledby="${id}-heading"><div class="wrap"><div class="pish-section-head"><span class="pish-section-number">${n}</span><div><p class="eyebrow">${esc(L(ctx,'ПИШ · от идеи к работающему станку','PISH · from an idea to a working machine'))}</p><h2 id="${id}-heading">${esc(title)}</h2>${sub?`<p class="section-lead">${esc(sub)}</p>`:''}</div></div>${body}</div></section>`;
const BASE_IDS=['machining','coatings-tribology','metrology-quality','ceramics-composites','metals-alloys'];
const CHECK_IDS=['ai-data','modeling-mechanics','machine-tools-control','condition-monitoring','robotics'];

export function pishLoopSpec(ctx) {
  const nodes=[
    {id:'tool',label:L(ctx,'Материал и инструмент','Material and tool'),subtitle:L(ctx,'Покрытие · геометрия · износ','Coating · geometry · wear'),status:'strong',statusLabel:L(ctx,'Есть исследования','Published research')},
    {id:'cutting',label:L(ctx,'Обработка резанием','Machining'),subtitle:L(ctx,'Силы · вибрации · режимы','Forces · vibration · parameters'),status:'strong',statusLabel:L(ctx,'Есть исследования','Published research')},
    {id:'signals',label:L(ctx,'Измерить состояние','Measure condition'),subtitle:L(ctx,'Датчики · зрение · метрология','Sensors · vision · metrology'),status:'build',statusLabel:L(ctx,'Собрать и испытать','Build and test')},
    {id:'model',label:L(ctx,'Модель резания + ИИ','Process model + AI'),subtitle:L(ctx,'Физика · данные · проверка','Physics · data · tests'),status:'build',statusLabel:L(ctx,'Собрать и испытать','Build and test')},
    {id:'uncertainty',label:L(ctx,'Прогноз с интервалом','Predict with uncertainty'),subtitle:L(ctx,'Ошибка · надёжность прогноза','Error · prediction reliability'),status:'verify',statusLabel:L(ctx,'Нужно проверить','Needs testing')},
    {id:'correction',label:L(ctx,'Изменить режим','Adjust parameters'),subtitle:L(ctx,'ЧПУ · пределы · журнал действий','CNC · limits · action log'),status:'verify',statusLabel:L(ctx,'Требуется партнёр','Partner required')},
    {id:'acceptance',label:L(ctx,'Независимая приёмка','Independent acceptance'),subtitle:L(ctx,'Точность · брак · стоимость','Accuracy · rejects · cost'),status:'verify',statusLabel:L(ctx,'Заказчик принимает','Customer accepts')},
  ];
  return {lang:ctx.lang,nodes:nodes.map(n=>({...n,href:`#pish-node-${n.id}`}))};
}

function competencyChips(ctx,ids) {
  return `<ul class="pish-chips">${ids.map(id=>{const r=ctx.model.pish.rows.find(x=>x.id===id);return `<li><a href="${esc(ctx.page(`competencies/${id}/`))}">${esc(ctx.compShort(id))}</a>${r?`<b>${esc(ctx.int(r.n))}</b>`:''}</li>`;}).join('')}</ul>`;
}

function uncertaintyTable(ctx,rows) {
  const data=table([
    {key:'name',label:L(ctx,'Направление','Field')},
    {key:'p1',label:`FWCI ${periodLabel(ctx,'p1')} · 95%`,num:true},
    {key:'p2',label:`FWCI ${periodLabel(ctx,'p2')} · 95%`,num:true},
    {key:'difference',label:L(ctx,'Второе минус первое · 95%','Second minus first · 95%'),num:true},
    {key:'withoutMax',label:L(ctx,'FWCI без работы с максимальным FWCI','FWCI without the highest-FWCI work'),num:true},
    {key:'top3',label:L(ctx,'Вклад трёх работ в сумму FWCI','Three works’ share of FWCI sum'),num:true},
  ],rows.map(r=>({cells:{
    name:text(ctx.compShort(r.id)),
    p1:cell(`${esc(interval(ctx,r.cohorts.p1.fwciCI95))}<small class="pish-cohort-label">n=${ctx.int(r.cohorts.p1.fwciN)}</small>`,r.cohorts.p1.fwci),
    p2:cell(`${esc(interval(ctx,r.cohorts.p2.fwciCI95))}<small class="pish-cohort-label">n=${ctx.int(r.cohorts.p2.fwciN)}</small>`,r.cohorts.p2.fwci),
    difference:cell(esc(interval(ctx,r.fwciDifferenceCI95)),r.fwciDifferenceCI95?.estimate),
    withoutMax:cell(`${esc(value(ctx,r.influence?.withoutMax?.fwci,3))}${r.influence?.maxWork?.id?`<small class="pish-cohort-label"><a href="https://openalex.org/${esc(r.influence.maxWork.id)}">${esc(L(ctx,'Посмотреть эту работу','Inspect this work'))}</a></small>`:''}`,r.influence?.withoutMax?.fwci),
    top3:cell(percent(ctx,r.influence?.top3?.shareOfFwciSum),r.influence?.top3?.shareOfFwciSum),
  }})));
  return `<details class="chart-table pish-statistics"><summary>${esc(L(ctx,'Насколько надёжны эти числа','How reliable are these numbers?'))}</summary>${data}<p class="pish-caption">${esc(L(ctx,'Среднее сохранённой базы известно точно. Для проверки его чувствительности показаны 95% bootstrap-интервалы: 2 000 раз выбираем работы с повторениями и пересчитываем среднее, считая работы независимыми. Если доступно меньше 20 значений, интервал не строится.', 'The mean of the saved corpus is known exactly. To check its sensitivity, 95% bootstrap intervals draw works with replacement 2,000 times and recalculate the mean, assuming independent works. No interval is calculated with fewer than 20 valid values.'))}</p><p class="pish-caption">${esc(L(ctx,'Интервалы не исправляют ошибки тематики и аффилиаций. Сравнения исследовательские, без поправки на множественность; они не доказывают, какое направление лучше всех. FWCI учитывает год, тип работы и область, но четырёхлетнее окно цитирования работ 2023–2025 ещё не завершено. Разница средних не доказывает изменение качества науки. Расчёт без одной работы и вклад трёх работ относятся ко всему периоду.', 'Intervals do not correct topic or affiliation errors. Comparisons are exploratory, without adjustment for multiple comparisons; they do not establish a best field. FWCI adjusts for year, document type and field, but the four-year citation window for 2023–2025 works is still incomplete. A difference in means does not prove a change in research quality. Single-work omission and three-work contribution use the full period.'))} <a href="https://help.openalex.org/data/works/citations/" rel="noopener">${esc(L(ctx,'Как OpenAlex считает FWCI','How OpenAlex calculates FWCI'))}</a></p><a href="${esc(ctx.asset('data/pish.json'))}" download>${esc(L(ctx,'Скачать данные, интервалы и параметры расчёта','Download data, intervals and calculation settings'))}</a></details>`;
}

function nodeMath(ctx,id) {
  if(id==='signals') return `<p class="math">MAE<sub>VB</sub> = (1/N) Σ |VB<sub>i</sub> − V̂B<sub>i</sub>| ≤ 20 ${esc(L(ctx,'мкм','µm'))}</p><p>${esc(L(ctx,'Средняя ошибка оценки износа. 20 мкм — цель для испытаний, а не полученный результат.', 'Mean wear-estimation error. The 20 µm value is a test target, not an achieved result.'))}</p>`;
  if(id==='model') return `<p>${esc(L(ctx,'Научную новизну ещё нужно определить под задачу заказчика: новый способ прогноза, работа при смене станка или управление с учётом ошибки модели. Название «умный станок» само по себе новизну не доказывает. Для проверки сравнивают физическую модель без ИИ, простой алгоритм и предложенный метод на отдельных станках и сериях. Соседние сигналы одной серии нельзя случайно разнести между обучением и испытанием.', 'The customer task must define the scientific contribution: a new prediction method, adaptation to another machine or control that accounts for model error. The name “smart machine” alone does not establish novelty. Compare the physics model without AI, a simple algorithm and the proposed method on separate machines and batches. Adjacent signals from one batch must not be randomly split between training and testing.'))}</p>`;
  if(id==='uncertainty') return `<p class="math">PICP = (1/N) Σ 1[L<sub>i</sub> ≤ y<sub>i</sub> ≤ U<sub>i</sub>]<br>MPIW = (1/N) Σ (U<sub>i</sub> − L<sub>i</sub>)</p><p>${esc(L(ctx,'PICP — доля измерений внутри интервала; MPIW — его средняя ширина. Проверяем оба числа: широкий интервал легче накрывает результат, но хуже помогает выбрать режим. Интервалы прогноза 90% относятся к испытаниям станка; 95% bootstrap-интервалы выше — к среднему цитированию. Учёт неопределённости сам по себе не гарантирует допуск детали: результат всё равно проверяют независимым измерением.', 'PICP is the share of measurements inside the interval; MPIW is its mean width. Check both: a wide interval contains more outcomes but is less useful for choosing settings. The 90% prediction intervals concern machine tests; the 95% bootstrap intervals above concern mean citation impact. Accounting for uncertainty alone does not guarantee part tolerance: the result still needs an independent measurement.'))}</p>`;
  return '';
}

function worldFrontiers(ctx) {
  const selected=['T12111','T10220','T11948'].map(id=>(ctx.model.industrialTopics??[]).find(t=>t.id===id)).filter(Boolean);
  return `<div class="pish-world-frontiers"><div class="pish-frontier-intro"><span class="pish-pill">${esc(L(ctx,'Куда идёт мировая наука','Where world research is going'))}</span><h3>${esc(L(ctx,'Растёт интерес к зрению, диагностике и ИИ для материалов','Vision, diagnostics and materials AI draw growing interest'))}</h3><p>${esc(L(ctx,'Насколько выросла доля этих тем среди всех работ в мире за два пятилетия.', 'How these topics changed their share of all world publications between two five-year periods.'))}</p></div>${selected.map(t=>`<article><a href="https://openalex.org/${esc(t.id)}">${esc(phrase(ctx,t.name))}</a><strong>${change(ctx,t.worldShareRatio==null?null:t.worldShareRatio-1)}</strong><span>${esc(L(ctx,'Мировая доля темы','World topic share'))}</span><small>${esc(L(ctx,'СТАНКИН: ','STANKIN: '))}${esc(ctx.int(t.nP2))} · ${esc(periodLabel(ctx,'p2'))}</small></article>`).join('')}</div><p class="pish-caption">${esc(L(ctx,'Эти темы охватывают разные отрасли. Рост числа научных работ не доказывает рост рынка. Если OpenAlex не нашёл работы СТАНКИН с такой основной темой, это ещё не значит, что в вузе нет специалистов. Доля обычной механической обработки меняется мало; быстрее растут исследования зрения, диагностики и ИИ.', 'These topics span several industries. Publication growth does not prove market growth. No STANKIN works assigned to a primary OpenAlex topic does not mean that the university has no relevant specialists. The broad machining share changes little; vision, diagnostics and AI research grow faster.'))}</p>`;
}

function candidates(ctx) {
  const m=ctx.model.pish;
  const body=`<div class="pish-candidates">${PISH_CANDIDATES.map(c=>{const evidence=m.candidateEvidence?.[c.id];return `<article class="pish-candidate${c.recommended?' pish-recommended':''}"><div class="pish-candidate-status">${esc(c.recommended?L(ctx,'Предлагаем выбрать','Recommended for discussion'):L(ctx,'Альтернатива','Alternative'))}</div><h3>${esc(phrase(ctx,c.title))}</h3>${evidence?`<div class="pish-candidate-scale"><strong>${esc(ctx.int(evidence.n))}</strong><span>${esc(L(ctx,'работ по указанным направлениям','works in the listed fields'))}<br>${esc(ctx.int(evidence.nP2))} · 2021–2025</span></div>`:''}<dl><div><dt>${esc(L(ctx,'Есть исследования','Published research'))}</dt><dd>${esc(phrase(ctx,c.basis))}${competencyChips(ctx,c.competencyIds??[])}</dd></div><div><dt>${esc(L(ctx,'Мировой тренд','World trend'))}</dt><dd>${esc(phrase(ctx,c.trend))}</dd></div><div><dt>${esc(L(ctx,'Что получим','What we will deliver'))}</dt><dd>${esc(phrase(ctx,c.product))}</dd></div><div><dt>${esc(L(ctx,'Отличие от действующей ПИШ','Distinct from the current PISH'))}</dt><dd>${esc(phrase(ctx,c.distinction))}</dd></div><div><dt>${esc(L(ctx,'Что нужно доказать','Evidence still needed'))}</dt><dd>${esc(phrase(ctx,c.gaps))}</dd></div></dl><p class="pish-verdict">${esc(phrase(ctx,c.verdict))}</p>${sourceIds(ctx,c.sourceIds)}</article>`;}).join('')}</div><p class="pish-caption">${esc(L(ctx,'В каждой теме одна публикация считается один раз. Между темами работы могут повторяться. Эти числа показывают исследовательский опыт; спрос заказчика и готовность продукта нужно проверить отдельно. Баллы конкурса здесь не рассчитываются.', 'Each work is counted once within a topic; different topics may share works. The counts show research experience. Customer demand and product readiness need separate checks. No competition score is calculated here.'))}</p>`;
  return section(ctx,'pish-choice','01',L(ctx,'Какую тему выбрать','Which topic to choose'),L(ctx,'Предлагаем «Инженерию интеллектуальных станков и автономной точной обработки». Окончательный выбор зависит от того, какую задачу готов поставить и оплатить промышленный заказчик.', 'We propose “Engineering intelligent machine tools and autonomous precision machining”. The final choice depends on the task an industrial customer is willing to commission and fund.'),body+worldFrontiers(ctx));
}

function cohorts(ctx) {
  const m=ctx.model.pish;
  const ids=['machining','coatings-tribology','metrology-quality','ceramics-composites','metals-alloys','ai-data','modeling-mechanics','machine-tools-control','condition-monitoring','robotics'];
  const rows=ids.map(id=>m.rows.find(r=>r.id===id)).filter(Boolean);
  const spec={lang:ctx.lang,period:m.period,rows:rows.map(r=>({id:r.id,name:ctx.compShort(r.id),href:ctx.page(`competencies/${r.id}/`),p1:r.cohorts.p1,p2:r.cohorts.p2}))};
  const columns=[{key:'name',label:L(ctx,'Направление / годы работ','Field / publication years')},{key:'n',label:L(ctx,'Работы','Works'),num:true},{key:'fwci',label:'FWCI',num:true},{key:'median',label:L(ctx,'Медиана FWCI','FWCI median'),num:true},{key:'coverage',label:L(ctx,'Покрытие FWCI','FWCI coverage'),num:true},{key:'top',label:L(ctx,'В top 10%','In the top 10%'),num:true},{key:'topCoverage',label:L(ctx,'Покрытие top 10%','Top 10% coverage'),num:true},{key:'world',label:L(ctx,'Изменение мировой доли темы','World topic-share change'),num:true}];
  const data=table(columns,rows.flatMap(r=>['p1','p2'].map(p=>{const q=r.cohorts[p];return {cells:{name:cell(`<a href="${esc(ctx.page(`competencies/${r.id}/`))}">${esc(ctx.compShort(r.id))}</a><small class="pish-cohort-label">${esc(periodLabel(ctx,p))}${r.limited?` · ${esc(L(ctx,'ограниченные данные','limited evidence'))}`:''}</small>`,ctx.compShort(r.id)),n:cell(ctx.int(q.n),q.n),fwci:cell(value(ctx,q.fwci,3),q.fwci),median:cell(value(ctx,q.fwciMedian,3),q.fwciMedian),coverage:cell(`${percent(ctx,q.fwciCoverage)} (${ctx.int(q.fwciN)}/${ctx.int(q.n)})`,q.fwciCoverage),top:cell(`${percent(ctx,q.top10)}${q.top10CI95?`<small class="pish-cohort-label">Wilson 95%: ${percent(ctx,q.top10CI95.lower)} … ${percent(ctx,q.top10CI95.upper)}</small>`:''}`,q.top10),topCoverage:cell(percent(ctx,q.top10Coverage),q.top10Coverage),world:cell(p==='p2'?change(ctx,r.worldShareChange):'—',p==='p2'?r.worldShareChange:null)}};})),{sortable:true});
  const fig=figure(ctx,{id:'pish-cohorts',type:'pish-cohorts',spec,svg:cohortsChart(spec,1160),table:data,wide:true});
  const s=m.sensitivity;const topic=s?.selectedTopic??{};
  const sens=s?`<aside class="pish-sensitivity"><div><span class="pish-pill">${esc(L(ctx,'Что влияет на среднее','What affects the average'))}</span><h3>${esc(L(ctx,'Покрытия: несколько работ заметно меняют среднее','Coatings: a few works substantially change the average'))}</h3><p>${esc(L(ctx,'Сравним средний FWCI всех работ по покрытиям с расчётом без одной темы. Это проверка расчёта: сами публикации из базы не удаляются.', 'Compare mean FWCI for all coatings works with the calculation excluding one topic. This is a sensitivity check; no works are removed from the dataset.'))}</p><p class="pish-caption">${esc(typeof s.topicName==='string'?s.topicName:phrase(ctx,s.topicName))}${s.topicId?` · <a href="https://openalex.org/${esc(s.topicId)}">${esc(s.topicId)}</a>`:''}</p></div><div class="pish-sensitivity-values"><article><span>${esc(L(ctx,'Все работы','All works'))}</span><strong>${value(ctx,s.all?.fwci,3)}</strong><small>${esc(L(ctx,`FWCI · ${periodLabel(ctx)} · n=${s.all?.n??'—'}`,`FWCI · ${periodLabel(ctx)} · n=${s.all?.n??'—'}`))}</small></article><article><span>${esc(L(ctx,'Без выбранной темы','Without the selected topic'))}</span><strong>${value(ctx,s.withoutTopic?.fwci,3)}</strong><small>${esc(L(ctx,`FWCI · ${periodLabel(ctx)} · n=${s.withoutTopic?.n??'—'}`,`FWCI · ${periodLabel(ctx)} · n=${s.withoutTopic?.n??'—'}`))}</small></article><article><span>${esc(L(ctx,'Работ выбранной темы','Works in the selected topic'))}</span><strong>${esc(ctx.int(topic.n??0))}</strong><small>${esc(L(ctx,`FWCI ${value(ctx,topic.fwci,3)} · малая группа сдвигает среднее`,`FWCI ${value(ctx,topic.fwci,3)} · a small group shifts the mean`))}</small></article></div></aside>`:'';
  return section(ctx,'pish-evidence','02',L(ctx,'Что уже умеем — по публикациям','What the publications show we can build on'),L(ctx,'Сравним работы двух пятилетий: сколько их, как часто их цитируют и насколько среднее зависит от отдельных статей. FWCI учитывает год, тип работы и область; у работ 2023–2025 четырёхлетнее окно цитирования ещё не завершено.', 'Compare two five-year groups: publication counts, citation impact and the influence of individual papers on the average. FWCI adjusts for year, document type and field; the four-year citation window for 2023–2025 works is still incomplete.'),`${fig}${sens}${uncertaintyTable(ctx,rows)}<div class="pish-evidence-note"><p>${esc(L(ctx,'FWCI сравнивает цитирование с работами той же области, типа и года; здесь показано среднее доступных значений. Top 10% — доля работ среди самых цитируемых. Оба показателя считаются только по работам, для которых есть данные. Если работ мало, вывод предварительный.', 'FWCI compares citations with works in the same field, document type and year; the chart shows the mean of available values. Top 10% is the share among the most-cited works. Both measures use only works with the required data. Small samples make conclusions provisional.'))}</p><p>${esc(L(ctx,'У новых работ по покрытиям FWCI ниже. Нужно посмотреть, какие задачи решались и где появились сильные результаты. По одному среднему нельзя решать, закрывать ли направление или сколько денег в него вложить.', 'Recent coatings works have lower FWCI. Examine the questions studied and where strong results emerged. One average cannot determine whether to close a field or how much to invest.'))}</p></div>`);
}

function nodeDetails(ctx) {
  const nodes=[
    ['tool',L(ctx,'Материал, покрытие и режущий инструмент','Material, coating and cutting tool'),['coatings-tribology','ceramics-composites','metals-alloys'],L(ctx,'Ресурс инструмента, стойкость покрытия, механизм износа при заданной паре материал–инструмент.','Tool life, coating durability and wear mechanisms for a specified material–tool pair.'),L(ctx,'Модель износа и результаты испытаний. Инструмент для каждой серии готовят одинаково.','A wear model and test results, with the same tool preparation for every batch.'),L(ctx,'Инструментальщик · материаловед · технолог обработки','Tool engineer · materials scientist · machining engineer'),L(ctx,'Серия сопоставимых испытаний: ресурс и качество детали при одинаковой геометрии, материале и допуске.','Matched test series: tool life and part quality at the same geometry, material and tolerance.'),['cirp-machinability-2024','cirp-sustainable-2024']],
    ['cutting',L(ctx,'Как режем материал','How we machine the material'),['machining','laser-edm-plasma'],L(ctx,'Силы, температура, вибрации, точность, производительность и режимы резания.','Forces, temperature, vibration, accuracy, throughput and cutting parameters.'),L(ctx,'Стенд, проверенная модель резания и список допустимых режимов.','A test bench, a tested cutting model and a list of permitted settings.'),L(ctx,'Технолог обработки · специалист по динамике станка','Machining engineer · machine dynamics specialist'),L(ctx,'Сначала обработать серию обычным способом: заранее выбрать детали, допуски и способ измерения.','First machine a batch using the usual method, with parts, tolerances and measurement methods fixed in advance.'),['cirp-adaptive-2023','cirp-machinability-2024']],
    ['signals',L(ctx,'Как замечаем износ','How we detect wear'),['metrology-quality','condition-monitoring'],L(ctx,'Цель из презентации: средняя абсолютная ошибка (MAE) оценки ширины износа VB ≤20 мкм. Это ошибка оценки износа, а не предел самого износа. Цель ещё нужно проверить на станке.','Presentation target: mean absolute error (MAE) of tool-wear width VB estimation ≤20 µm. This is estimation error, not a wear limit. It still needs testing on a machine.'),L(ctx,'Сигналы с общей временной шкалой и контрольные измерения. Ошибку каждого датчика учитывают в общей погрешности.','Signals on a shared time scale and reference measurements. Include each sensor error in the total measurement uncertainty.'),L(ctx,'Метролог · специалист по датчикам и промышленному зрению','Metrologist · sensor and industrial vision specialist'),L(ctx,'Сверить показания системы с независимым измерением. Проверить, что происходит при дрейфе датчика и пропуске сигнала.','Check system estimates against independent measurements. Test sensor drift and missing signals.'),['cirp-metrology-2019']],
    ['model',L(ctx,'Как прогнозируем результат','How we predict the result'),['modeling-mechanics','ai-data'],L(ctx,'ŷ = f_phys(x,u) + r_θ(x,u). Модель описывает физику резания, а ИИ учится исправлять её ошибки. Цель: получить ответ за ≤10 мс.','ŷ = f_phys(x,u) + r_θ(x,u). The model describes cutting physics; AI learns to correct its errors. Proposed target: a prediction in ≤10 ms.'),L(ctx,'Рабочая модель и записи о том, на каких данных она обучена. Проверка на втором станке.','A working model with records of its training data and versions. A test on a second machine.'),L(ctx,'Исследователь процесса · разработчик модели · инженер программного обеспечения','Process researcher · model developer · software engineer'),L(ctx,'Испытывать на станках и сериях, которые модель не видела при обучении. Сравнить результат с физической моделью без ИИ и простыми алгоритмами.','Test on machines and batches unseen during training. Compare with the physics model without AI and simple algorithms.'),['cirp-adaptive-2023','nist-twins','ieee-uncertainty-2024']],
    ['uncertainty',L(ctx,'Насколько надёжен прогноз','How reliable the prediction is'),['ai-data','metrology-quality'],L(ctx,'Предлагаемый интервал прогноза — 90%. На отдельной испытательной серии в него должны попадать 85–95% измерений. Эти цели ещё нужно согласовать и проверить.','Proposed prediction interval: 90%. On a separate test batch, it should contain 85–95% of measurements. These targets still need agreement and testing.'),L(ctx,'Прогноз с указанием возможной ошибки. Система замечает режимы, на которых её ещё не обучали.','A prediction with its possible error. The system detects conditions it has not been trained for.'),L(ctx,'Специалист по статистике · метролог · инженер верификации','Statistician · metrologist · verification engineer'),L(ctx,'Отдельно проверить, как часто прогноз верен и насколько широк его интервал. Если уверенности недостаточно, система не меняет режим.','Check how often the interval is correct and how wide it is. With insufficient confidence, the system does not change settings.'),['nist-twins','ieee-uncertainty-2024']],
    ['correction',L(ctx,'Как меняем режим станка','How we change machine settings'),['machine-tools-control','robotics'],L(ctx,'В проекте цикл ЧПУ — 100 мкс, ответ модели — ≤10 мс. Это разные уровни управления. Модель может менять только параметры, заранее разрешённые разработчиком ЧПУ.','The proposed CNC cycle is 100 µs; model response is ≤10 ms. These are separate control layers. The model may change only settings pre-authorised by the CNC developer.'),L(ctx,'Подключение к ЧПУ, пределы изменения режима, возврат к исходному режиму и запись каждого действия.','A CNC connection, parameter limits, return to the original settings and a record of every action.'),L(ctx,'Разработчик ЧПУ · главный конструктор · производитель станка','CNC developer · chief designer · machine manufacturer'),L(ctx,'Согласовать правила с производителем. Проверить ограничения на стенде и работу системы на двух станках.','Agree the rules with the manufacturer. Test limits on a bench and run the system on two machines.'),['cirp-adaptive-2023','nist-twins','ieee-uncertainty-2024']],
    ['acceptance',L(ctx,'Что принимает заказчик','What the customer accepts'),['metrology-quality','machining'],L(ctx,'Стоимость годной детали, время цикла, ресурс инструмента и доля брака. Эффект считают относительно согласованной базовой серии.','Cost per accepted part, cycle time, tool life and reject share. Effects are measured against an agreed baseline batch.'),L(ctx,'Результаты измерений, расчёт затрат, акт приёмки заказчика и документация для внедрения.','Measurement results, a cost calculation, customer acceptance record and deployment documentation.'),L(ctx,'Квалифицированный заказчик · служба качества · инженерная команда ПИШ','Qualified customer · quality team · PISH engineering team'),L(ctx,'Одинаковые деталь, материал, допуск, нагрузка и метод учёта затрат; независимая приёмка серии, включая брак.','Same part, material, tolerance, load and cost accounting; independent acceptance of the whole batch, including rejects.'),['cirp-metrology-2019','pish-call-2026']],
  ];
  return `<div class="pish-node-details">${nodes.map(([id,title,ids,metric,result,role,accept,sources])=>`<details id="pish-node-${id}"><summary><span>${esc(title)}</span><span class="pish-detail-marker" aria-hidden="true">+</span></summary><div class="pish-detail-body"><dl><div><dt>${esc(L(ctx,'Что считаем','What we measure'))}</dt><dd>${esc(metric)}</dd></div><div><dt>${esc(L(ctx,'Что сдаём','What we deliver'))}</dt><dd>${esc(result)}</dd></div><div><dt>${esc(L(ctx,'Кто делает','Who does it'))}</dt><dd>${esc(role)}</dd></div><div><dt>${esc(L(ctx,'Как проверяем','How we check it'))}</dt><dd>${esc(accept)}</dd></div></dl>${nodeMath(ctx,id)}${competencyChips(ctx,ids)}${sourceIds(ctx,sources)}</div></details>`).join('')}</div>`;
}

function scientificLoop(ctx) {
  const spec=pishLoopSpec(ctx);
  const fig=figure(ctx,{id:'pish-scientific-loop',type:'pish-loop',spec,svg:pishLoop(spec,1160),wide:true});
  return section(ctx,'pish-product','03',L(ctx,'Как будет работать умный станок','How the smart machine will work'),L(ctx,'Задача новой ПИШ: станок замечает износ, подбирает режим в разрешённых пределах и проверяет деталь. Из уже опубликованных работ ещё предстоит собрать и испытать рабочую систему.', 'The proposed school will build a machine system that detects wear, adjusts permitted settings and checks the part. The published research still needs to be brought together and tested as a working system.'),`${fig}<div class="pish-maths"><article><span>${esc(L(ctx,'Модель','Model'))}</span><p class="math">ŷ = f<sub>phys</sub>(x,u) + r<sub>θ</sub>(x,u)</p><small>${esc(L(ctx,'Модель резания + поправка, обученная на данных','Cutting model + a correction learned from data'))}</small></article><article><span>${esc(L(ctx,'Когда можно менять режим','When settings may change'))}</span><p class="math">u′ ∈ U<sub>allowed</sub> · Q ≥ Q<sub>min</sub></p><small>${esc(L(ctx,'Меняем режим только в разрешённых пределах и при проверенной надёжности прогноза','Change settings only within permitted limits and with tested prediction reliability'))}</small></article><article><span>${esc(L(ctx,'Что получит производство','What the factory gains'))}</span><p class="math">C<sub>good</sub> = (C<sub>labor</sub> + C<sub>tool</sub> + C<sub>energy</sub> + C<sub>scrap</sub> + C<sub>overhead</sub>) / N<sub>accepted</sub></p><small>${esc(L(ctx,'Стоимость годной детали при сопоставимом допуске и нагрузке','Cost per accepted part at matched tolerance and load'))}</small></article></div><p class="pish-caption">${esc(L(ctx,'Это план разработки. 20 мкм — целевая ошибка оценки износа; 90% / 85–95% — цели для проверки интервала прогноза; 10 мс и 100 мкс — принятые в концепции времена работы. Всё это ещё предстоит испытать. Экономию считают после сравнения с обычной обработкой той же детали.', 'This is a development plan. The 20 µm value is a target wear-estimation error; 90% / 85–95% are targets for checking prediction intervals; 10 ms and 100 µs are the proposed timings. All require testing. Savings must be measured against conventional machining of the same part.'))}</p>${nodeDetails(ctx)}`);
}

function cooperation(ctx) {
  const body=`<div class="pish-cooperation"><article class="pish-role pish-role-base"><span class="pish-pill">${esc(L(ctx,'Есть работы по теме','Published work exists'))}</span><h3>${esc(L(ctx,'Что берём на себя в СТАНКИН','What STANKIN will take on'))}</h3>${competencyChips(ctx,BASE_IDS)}<p>${esc(L(ctx,'Материалы, покрытия, инструмент, резание и измерение деталей. Публикации показывают опыт в этих задачах. Теперь нужно выбрать кафедры, специалистов и оборудование для проекта.', 'Materials, coatings, tooling, cutting and part measurement. Publications show experience in these tasks. The project now needs named departments, engineers and equipment.'))}</p></article><article class="pish-role pish-role-check"><span class="pish-pill">${esc(L(ctx,'Проверить команду и оборудование','Check the team and equipment'))}</span><h3>${esc(L(ctx,'Где нужно усиление','Where we need help'))}</h3>${competencyChips(ctx,CHECK_IDS)}<p>${esc(L(ctx,`${ctx.int(ctx.model.pish.candidateEvidence?.ai?.n)} работ в широкой группе ИИ / данных включают классические методы и задачи вне производства. Число работ именно по ИИ для станков не установлено. Нужны конкретная команда, данные и станки для испытаний.`, `The broad AI / data group includes ${ctx.int(ctx.model.pish.candidateEvidence?.ai?.n)} works spanning classical methods and non-manufacturing tasks. The count specifically on machine-tool AI is not established. We need a named team, data and machines for testing.`))}</p></article><article class="pish-role pish-role-partner"><span class="pish-pill">${esc(L(ctx,'Партнёр ещё не выбран','Partner not yet selected'))}</span><h3>${esc(L(ctx,'Квалифицированный заказчик','Qualified industrial customer'))}</h3><ul class="pish-role-list"><li>${esc(L(ctx,'Производитель станка / ЧПУ: станок и подключение','Machine / CNC maker: machine and connection'))}</li><li>${esc(L(ctx,'Производство: детали, данные и место испытаний','Manufacturer: parts, data and a test site'))}</li><li>${esc(L(ctx,'Приёмка продукта и софинансирование','Product acceptance and co-financing'))}</li></ul><p>${esc(L(ctx,'Можно начать переговоры с компаниями действующей ПИШ. Для новой заявки нужны отдельные соглашения об их работе, финансировании и приёмке продукта.', 'Talks can begin with the current school partners. The new application needs separate agreements on their work, funding and product acceptance.'))}</p></article></div><div class="pish-cooperation-rule"><strong>${esc(L(ctx,'Один ответственный заказчик → один главный конструктор → согласованный продукт','One accountable customer → one chief designer → an agreed product'))}</strong><span>${esc(L(ctx,'Не более пяти организаций, включая головной вуз; обоснованность кооперации и управления — 40% оценки конкурса.', 'No more than five organisations, including the lead university; cooperation and its management account for 40% of the competition assessment.'))}</span>${sourceIds(ctx,['pish-call-2026'])}</div>`;
  return section(ctx,'pish-cooperation','04',L(ctx,'Что делаем сами, кого зовём в партнёры','What we do ourselves and where partners help'),L(ctx,'Для каждой задачи нужны ответственный и способ проверки результата. По числу статей нельзя узнать, есть ли подходящий станок и кто готов на нём работать.', 'Each task needs an owner and a way to check the result. Paper counts cannot tell us whether the right machine is available or who can operate it.'),body);
}

function continuity(ctx) {
  const body=`<div class="pish-continuity"><article><span class="pish-pill">${esc(L(ctx,'Действующая ПИШ','Existing PISH'))}</span><h3>${esc(L(ctx,'Инструмент · узлы · инжиниринг','Tooling · components · engineering'))}</h3><p>${esc(L(ctx,'В действующей школе уже занимаются инструментом, узлами станков и проектированием производств. Это следует из опубликованных результатов.', 'The existing school works on tooling, machine components and factory engineering, as shown by its published results.'))}</p>${sourceIds(ctx,['stankin-pish-results-2025'])}</article><div class="pish-continuity-join" aria-hidden="true">+</div><article><span class="pish-pill pish-pill-conditional">${esc(L(ctx,'ЦКП · заявка рассматривается','CKP · application under review'))}</span><h3>${esc(L(ctx,'Оборудование · данные · методы','Equipment · data · methods'))}</h3><p>${esc(L(ctx,'Если заявку ЦКП «Искусственный интеллект в машиностроении» поддержат, его оборудование и данные смогут помочь ПИШ. Пока решение не принято, считать их доступными нельзя.', 'If the “AI in mechanical engineering” shared facility application is approved, its equipment and data could support the school. Until a decision is made, they cannot be treated as available.'))}</p></article><div class="pish-continuity-join" aria-hidden="true">→</div><article class="pish-continuity-new"><span class="pish-pill">${esc(L(ctx,'Новая обособленная ПИШ','New separate PISH'))}</span><h3>${esc(L(ctx,'Умная обработка + испытания на производстве','Smart machining + factory tests'))}</h3><p>${esc(L(ctx,'Новая школа разрабатывает и испытывает систему управления обработкой на разных станках, готовит инженеров и внедряет продукт. В заявке нужно показать, чем этот продукт отличается от разработок действующей ПИШ.', 'The new school develops and tests a machining-control system on different machines, trains engineers and deploys the product. The application must explain how it differs from the existing school developments.'))}</p>${sourceIds(ctx,['pish-call-2026'])}</article></div><div class="pish-boundary"><span>${esc(L(ctx,'У каждого проекта своя работа','Each project has its own job'))}</span><p>${esc(L(ctx,'ЦКП даёт оборудование, данные и методы исследования. ПИШ готовит команду и сдаёт заказчику работающий продукт. Если ЦКП не поддержат, для заявки ПИШ потребуется другой план оборудования и доступа к данным.', 'The shared facility provides equipment, data and research methods. The school trains a team and delivers a working product to the customer. If the facility is not approved, the school application needs another equipment and data-access plan.'))}</p></div>`;
  return section(ctx,'pish-continuity','05',L(ctx,'Как новая ПИШ связана с действующей школой и ЦКП','How the new school relates to the existing school and shared facility'),L(ctx,'Используем опыт действующей школы. Для новой заявки отдельно определяем продукт, команду, заказчика и ответственность.', 'Use the existing school experience. Define the new product, team, customer and responsibilities separately.'),body);
}

function requirements(ctx) {
  const minimums=table([{key:'label',label:L(ctx,'Обязательный показатель','Mandatory indicator')},{key:'value',label:L(ctx,'Минимум','Minimum'),num:true},{key:'unit',label:L(ctx,'Единица / основание','Unit / basis')}],PISH_MINIMUMS.map(r=>({cells:{label:cell(`${esc(phrase(ctx,r.label))}${r.note?`<small class="pish-cohort-label">${esc(phrase(ctx,r.note))}</small>`:''}`,phrase(ctx,r.label)),value:cell(Object.entries(r.values??{}).map(([year,n])=>`<span data-pish-year="${esc(year)}"${year==='2031'?'':' hidden'}>${n==null?esc(L(ctx,'Н/П','N/A')):esc(ctx.dec(n,2))}</span>`).join(''),r.values?.[2031]),unit:text(phrase(ctx,r.unit))}})));
  return section(ctx,'pish-rules','К',L(ctx,'Что требует конкурс','What the competition requires'),L(ctx,`Третья волна ПИШ, документы Минобрнауки. Проверено ${ctx.date(PISH_REVIEWED_AT)}. Ниже требования конкурса; предложенная тема должна им соответствовать.`, `Third-wave PISH competition, Ministry documents. Reviewed ${ctx.date(PISH_REVIEWED_AT)}. These are competition requirements; the proposed topic must meet them.`),`<div class="pish-requirement-grid">${PISH_REQUIREMENTS.map(r=>`<article><strong>${esc(phrase(ctx,r.value))}</strong><h3>${esc(phrase(ctx,r.label))}</h3><p>${esc(phrase(ctx,r.detail))}</p>${sourceIds(ctx,r.sourceIds??['pish-call-2026'])}</article>`).join('')}</div><div class="pish-minimum-head"><div><h3>${esc(L(ctx,'Минимумы, которые надо заложить в заявку','Minimums the application must include'))}</h3><p>${esc(L(ctx,'Выбранный год: ','Selected year: '))}<strong data-pish-selected-year>2031</strong> · ${esc(L(ctx,'Н/П: не применяется; бюджетное финансирование на этот год не предусмотрено','N/A: not applicable; budget funding is not envisaged for that year'))}</p></div><label>${esc(L(ctx,'Год программы','Programme year'))}<select data-pish-horizon aria-label="${esc(L(ctx,'Год минимальных показателей','Minimum-indicator year'))}">${Array.from({length:8},(_,i)=>2027+i).map(y=>`<option value="${y}"${y===2031?' selected':''}>${y}</option>`).join('')}</select></label></div><div class="pish-minimum-table">${minimums}</div><p class="pish-caption">${esc(L(ctx,'Значения взяты из официального приложения. В одних строках указан результат за год, в других — за всё время с начала программы. Для заявки нужно свериться с полными документами конкурса.', 'The values come from the official annex. Some rows are annual; others accumulate from the start of the programme. Check the full competition documents when preparing the application.'))} ${sourceIds(ctx,['pish-call-2026'])}</p>`);
}

function roadmap(ctx) {
  const stages=[['2027',L(ctx,'Требования заказчика','Customer requirements'),L(ctx,'Деталь, допуск, базовая серия, продукт и ответственность','Part, tolerance, baseline, product and accountability'),L(ctx,'Утверждён протокол приёмки','Acceptance protocol agreed')],['2028',L(ctx,'Испытательный стенд','Test bench'),L(ctx,'Сигналы, физическая модель, интервалы и пределы коррекции','Signals, physics model, intervals and correction limits'),L(ctx,'Система испытана на новых деталях','System tested on a fresh batch')],['2029',L(ctx,'Перенос между станками','Transfer between machines'),L(ctx,'Две платформы, общий интерфейс и проверка переноса','Two platforms, common interface and transfer verification'),L(ctx,'Результат повторён на втором станке','Result repeated on a second machine')],['2031',L(ctx,'Продукт, который принял заказчик','Customer-accepted product'),L(ctx,'Испытать на производстве → внедрить, подготовить инженеров','Factory trial → deployment, engineers trained'),L(ctx,'Подтверждены качество детали и стоимость обработки','Part quality and machining cost verified')],['2036',L(ctx,'Автономные системы','Autonomous systems'),L(ctx,'Объединить проверенные станки, автоматизировать переналадку, сохранить историю каждой детали','Connect tested machines, automate changeovers and record each part history'),L(ctx,'Возможное продолжение после проверки первых станков','Possible next step after the first machines are proven')]];
  const decisions=[L(ctx,'Какой продукт делаем','Which product we build'),L(ctx,'Квалифицированный заказчик','Qualified customer'),L(ctx,'Главный конструктор','Chief designer'),L(ctx,'Кого берём в команду','Who joins the team')];
  return section(ctx,'pish-roadmap','06',L(ctx,'Что должны получить к 2031 году','What we should deliver by 2031'),L(ctx,'Предлагаемый план: к 2031 году заказчик получает работающую систему с проверенными качеством и затратами. После этого можно обсуждать автономное производство к 2036 году.', 'Proposed plan: by 2031 the customer receives a working system with verified quality and costs. Autonomous production towards 2036 can be considered after that.'),`<ol class="pish-roadmap">${stages.map(([year,title,work,gate],i)=>`<li class="${i===4?'pish-stage-vision':''}"><span class="pish-year">${year}</span><h3>${esc(title)}</h3><p>${esc(work)}</p><strong><span>${esc(L(ctx,'Приёмка','Gate'))}</span>${esc(gate)}</strong></li>`).join('')}</ol><div class="pish-meeting"><div><p class="eyebrow">${esc(L(ctx,'Решения совещания','Meeting decisions'))}</p><h3>${esc(L(ctx,'О чём договориться на совещании','What to agree at the meeting'))}</h3></div><ol>${decisions.map((d,i)=>`<li><span>${i+1}</span>${esc(d)}</li>`).join('')}</ol><p>${esc(L(ctx,'После совещания вместе с заказчиком описать продукт, условия его приёмки и обязательства каждого участника. Эти документы станут основой заявки.', 'After the meeting, agree the product, acceptance conditions and each participant commitment with the customer. These documents will form the basis of the application.'))}</p></div>`);
}

function sources(ctx) {
  return `<section class="section pish-sources" id="pish-sources"><div class="wrap"><h2>${esc(L(ctx,'Откуда взяты данные и что ещё нужно проверить','Where the data come from and what remains to be checked'))}</h2><p class="pish-caption">${esc(L(ctx,'Публикации взяты из OpenAlex, требования — из документов конкурса. Схема основана на научных обзорах и авторской презентации. Это предложение: из исследований ещё предстоит собрать и испытать работающую систему.', 'Publications come from OpenAlex; requirements come from competition documents. The diagram draws on research reviews and the supplied presentation. This is a proposal: the research still needs to be assembled and tested as a working system.'))}</p><ol>${PISH_SOURCES.map(s=>`<li id="pish-source-${esc(s.id)}"><a href="${esc(s.url)}" rel="noopener">${esc(phrase(ctx,s.title))}</a><small>${esc([s.publisher,s.year,s.section?phrase(ctx,s.section):null].filter(Boolean).join(' · '))}</small></li>`).join('')}</ol><div class="pish-downloads"><a href="${esc(ctx.asset('data/pish.json'))}" download>${esc(L(ctx,'Расчёт, показатели и условия · JSON','Calculations, indicators and conditions · JSON'))}</a><a href="${esc(ctx.asset(`data/pish-loop-${ctx.lang}.svg`))}" download>${esc(L(ctx,'Научная схема · SVG','Scientific diagram · SVG'))}</a><a href="${esc(ctx.page('method/'))}">${esc(L(ctx,'Методика и аудит аффилиаций','Method and affiliation audit'))}</a></div></div></section>`;
}

export function pishPage(ctx) {
  const m=ctx.model.pish;const svgUrl=ctx.asset(`data/pish-loop-${ctx.lang}.svg`);
  const nav=[['pish-choice',L(ctx,'Тема','Topic')],['pish-evidence',L(ctx,'Доказательства','Evidence')],['pish-product',L(ctx,'Научная схема','Scientific model')],['pish-cooperation',L(ctx,'Кооперация','Cooperation')],['pish-rules',L(ctx,'Конкурс','Competition')],['pish-roadmap',L(ctx,'Рубежи','Gates')]];
  return `<section class="hero pish-hero"><div class="wrap"><div class="pish-hero-top"><p class="eyebrow">${esc(L(ctx,'ПИШ · третья волна · подготовка к совещанию','PISH · third wave · meeting preparation'))}</p><span class="pish-pill pish-pill-conditional">${esc(L(ctx,'Предложение для обсуждения','Proposal for discussion'))}</span></div><h1>${esc(L(ctx,'Умный станок: какую ПИШ предложить СТАНКИН','Smart machine tools: a new engineering school for STANKIN'))}</h1><p class="lead">${esc(L(ctx,'Инженерия интеллектуальных станков и автономной точной обработки','Engineering intelligent machine tools and autonomous precision machining'))}</p><div class="pish-hero-outcome"><strong>${esc(L(ctx,'Измерить → предсказать → скорректировать → принять деталь','Measure → predict → correct → accept the part'))}</strong><p>${esc(L(ctx,'В СТАНКИН есть исследования материалов, инструмента, резания и измерений. Предлагаем собрать из них систему для умного станка. ИИ и управление нужно усилить вместе с партнёрами; продукт выбираем под задачу заказчика.', 'STANKIN has research in materials, tooling, machining and measurement. We propose bringing it together in a smart-machine system. AI and control need partner support; the product must answer a customer task.'))}</p></div><div class="pish-toolbar"><button type="button" data-pish-projector aria-pressed="false">${esc(L(ctx,'Режим проектора','Projector mode'))}</button><button type="button" data-pish-print>${esc(L(ctx,'Печатная версия','Print version'))}</button><a href="${esc(svgUrl)}" download>${esc(L(ctx,'Скачать схему SVG','Download SVG diagram'))}</a><a href="${esc(ctx.page('decisions/'))}">${esc(L(ctx,'Карта научных компетенций','Research competency map'))} →</a></div><p class="data-note">${esc(ctx.int(m.totalWorks))} ${esc(L(ctx,`работ ${periodLabel(ctx)} · снимок`,`works, ${periodLabel(ctx)} · snapshot`))} ${esc(ctx.date(m.fetchedAt))} · ${m.excludedWorks==null?'—':esc(ctx.int(m.excludedWorks))} ${esc(L(ctx,'ошибочно приписанных вузу работ исключено','misattributed works excluded'))}</p></div></section><nav class="pish-section-nav wrap" aria-label="${esc(L(ctx,'Разделы подготовки заявки ПИШ','PISH preparation sections'))}">${nav.map(([id,label])=>`<a href="#${id}">${esc(label)}</a>`).join('')}</nav>${candidates(ctx)}${cohorts(ctx)}${scientificLoop(ctx)}${cooperation(ctx)}${continuity(ctx)}${requirements(ctx)}${roadmap(ctx)}${sources(ctx)}`;
}
